class Idioma:

    ATUAL = "pt"

    TEXTOS = { # portugues 
        "pt": {

            # Comuns a várias telas
            "comum.id": "ID", #classe com o seu valor 
            "comum.nome": "Nome",
            "comum.novo": "Novo",
            "comum.salvar": "Salvar",
            "comum.alterar": "Alterar",
            "comum.excluir": "Excluir",
            "comum.fechar": "Fechar",
            "comum.cancelar": "Cancelar",
            "comum.confirmacao": "Confirmado!",
            "comum.erro_prefixo": "Erro: ",

            #Tela de Animal
            "animal.janela_titulo": "CRUD de Animais",
            "animal.titulo" : "Cadastro de animal",
            "animal.dados_frame": "Dados do Animal",
            "animal.sexo": "Sexo:",
            "animal.peso": "Peso:",
            "animal.data_nascimento": "Data de Nascimento:",
            "animal.cliente_id": "Cliente ID:",
            "animal.especie_id": "Espécie ID:",
            "animal.raca_id": "Raça ID:",
            "animal.confirmacao_exclusao": "Deseja realmente excluir este animal?",
            "animal.selecionar_animal": "Selecione um animal na lista.",
            "animal.atualizacao": "Animal atualizado com sucesso!",
            "animal.cadastro": "Animal cadastrado com sucesso!",
            "animal.exclusao": "Animal excluído com sucesso!",
            "animal.nao_encontrado": "Animal não encontrado.",
            "animal.problema_exclusao": "Problemas ao excluir animal",

            #Tela de Aplicacao_vacina
            "aplicacao_vacina.janela_titulo": "CRUD de Aplicações de Vacina",
            "aplicacao_vacina.titulo": "Criação de aplicação de vacina",
            "aplicacao_vacina.dadso_frame": "Dados da Aplicação de Vacina",
            "aplicacao_vacina.tipo_servico": "Tipo de Serviço:",
            "aplicacao_vacina.data_vacina": "Data Vacina:",
            "aplicacao_vacina.horario_vacina": "Horário Vacina:",
            "aplicacao_vacina.status_vacina": "Status Vacina:",
            "aplicacao_vacina.animal_id": "Animal ID:",
            "aplicacao_vacina.vacina_id": "Vacina ID:",
            "aplicacao_vacina.confirmacao_exclusao": "Deseja realmente excluir esta aplicação de vacina?",
            "aplicacao_vacina.cadastro_sucesso": "Aplicação da vacina cadastrada com sucesso!",
            "aplicacao_vacina.selecionar_aplicacao": "Selecione uma aplicação da vacina na lista.",
            "aplicacao_vacina.atualizacao": "Aplicação da vacina atualizada com sucesso!",
            "aplicacao_vacina.exclusao_sucesso": "Aplicação da vacina excluída com sucesso!",
            "aplicacao_vacina.nao_encontrado": "Aplicação da vacina não encontrado",
            "aplicacao_vacina.problema_exclusao": "Problemas ao excluir a aplicação da vacina.",

            #Tela de Vacina
            "vacina.cadastro_sucesso": "Vacina cadastrada com sucesso!",
            "vacina.selecionar_vacina": "Selecione uma vacina na lista.",
            "vacina.atualizacao": "Vacina atualizada com sucesso!",
            "vacina.exclusao": "Vacina excluída com sucesso!",
            "vacina.nao_encontrada": "Vacina não encontrada.",
            "vacina.problema_exclusao": "Problemas ao excluir vacina",
            "vacina.janela_titulo": "CRUD de Vacinas",
            "vacina.titulo": "Criação de vacina",
            "vacina.dados_frame": "Dados da Vacina",
            "vacina.descricao": "Descricao",
            "vacina.confirmacao_exclusao": "Deseja realmente excluir esta vacina?",
            "vacina.titulo": "Criação de vacina",

            #Tela de Cliente
            "cliente.janela_titulo" : "Crud de Clientes",
            "cliente.titulo" : "Cadastro de cliente",
            "cliente.dados_frame" : "Dados do cliente",
            "cliente.telefone" : "Numero de telefone:",
            "cliente.cpf" : "Numero do CPF:",
            "cliente.confirmacao_exclusao" : "Deseja realmente excluir este cliente?",
            "cliente.selecionar_animal" : "Selecione um animal",
            "cliente.cadastro_sucesso" : "Cliente cadastrado com sucesso!",
            "cliente.problema_exclusao" : "Problemas ao excluir cliente!!",
            "cliente.atualizacao" : "Cliente atualizado!",
            "cliente.selecionar" : "Selecione um cliente",
            "cliente.exclusao" : "Cliente excluido com sucesso!",
            "cliente.nao_encontrado" : "Nenhum cliente encontrado!",

            #Tela de Raça
            "raca.janela_titulo": "CRUD de Raças",
            "raca.titulo": "Cadastro de raça",
            "raca.dados_frame": "Dados da raça",
            "raca.confirmacao_exclusao": "Deseja realmente excluir esta raça?",
            "raca.cadastro_sucesso": "Raça cadastrada com sucesso!",
            "raca.selecione_raca": "Selecione uma raça da lista",
            "raca.raca_atualizada": "Raça atualizada",
            "raca.exclusao": "Raça excluida com sucesso",
            "raca.nao_encontrada": "Raça nao encontrada",
            "raca.problema_exclusao": "Problemas ao excluir raça",
        
            #Tela de Agendamento
            "agendamento.janela_titulo": "Crud de agendamentos",
            "agendamento.titulo": "Cadastro de agendamento",
            "agendamento.dados": "Dados do agendamento",
            "agendamento.servico": "Serviços",
            "agendamento.horario": "Horario",
            "agendamento.data_agendamento": "Data do agendamento",
            "agendamento.status": "Status:",
            "agendamento.confirmacao_exclusao": "Deseja realmente excluir este agendamento?",
            "agendamento.cadastro_sucesso": "Agendamento cadastrado",
            "agendamento.selecione_agendamento": "Selecione um agendamento da lista",
            "agendamento.atualizado": "Agendamento atualizado",
            "agendamento.exclusao": "Agendamento excluido",
            "agendamento.nao_encontrado": "Agendamento nao encontrado",
            "agendamento.problema_exclusao": "Problomas ao excluir agendamento",
            "agendamento.animal_id": "Animal ID:",
            "agendamento.status_agendamento": "Status do agendamento",
            "agendamento.data": "Data",

            #Tela de Especie
            "especie.janela_titulo": "Cadastro de especies",
            "especie.crud_de_especie": "CRUD de espécie",
            "especie.dados": "Dados da Especie",        
            "especie.adicionar_raca": "Adicionar raça",
            "especie.confirmacao_exclusao": "Deseja mesmo excluir esta especie?",
            "especie.selecionar_raca": "Selecione uma raça!",
            "especie.cadastro": "Espécie cadastrada com sucesso!",
            "especie.selecione_especie": "Selecione uma espécie!",
            "especie.raca_a_especie": "Raça adicionada à espécie com sucesso!",
            "especie.atualizada": "Espécie atualizada com sucesso!",
            "especie.exclusao": "Espécie excluída com sucesso!",
            "especie.nao_encontrada": "Espécie não encontrada!",
            "especie.problema_exclusao": "Problemas ao excluir espécie.",

            #Tela de Consulta
            "consulta.janela_titulo": "CRUD de consultas",
            "consulta.titulo": "Cadastro de Consulta",
            "consulta.dados": "Dados Consulta",
            "consulta.horario": "Horário de consulta",
            "consulta.data": "Data da consulta",
            "consulta.observacao": "Observações",
            "consulta.confirmacao_exclusao": "Deseja mesmo excluir esta consulta?",
            "consulta.selecione_veterionario": "Selecione um veterinário!",
            "consulta.agendamento": "Consulta agendada com sucesso!",
            "consulta.erro_cadastro": "Erro ao cadastrar consulta!",
            "consulta.atualizacao": "Consulta Atualizada com Sucesso!",
            "consulta.selecione_consulta": "Selecione uma consulta da lista:",
            "consulta.nao_encontrada": "Consulta não encontrada!",
            "consulta.erro_exclusao": "Erro ao exclur Consulta",
            "consulta.veterinario" : "Veterinário",
            "consulta.excluida_sucesso": "Consulta excluída com sucesso!",

            #Tela de Veterinario
            "veterinario.janela_titulo": "CRUD Veterinários",
            "veterinario.titulo": "Cadastro de Veterinários",
            "veterinario.dados": "Dados do Veterinário",
            "veterinario.telefone": "Telefone: ",
            "veterinario.cpf": "CPF do Veterinário:",
            "veterinario.rg": "RG",
            "veterinario.especialidade": "Especialidade:",
            "veterinario.confirmacao_exclusao": "Deseja realmente excluir esse veterinário?",
            "veterinario.cadastro": "Veterinario Cadastrado com sucesso!",
            "veterinario.selecione_veterinario": "Selecione um veterinario da lista:",
            "veterinario.atualizacao": "Veterinario atualizado com sucesso!",
            "veterinario.exclusao": "Veterinario excluído com sucesso!",
            "veterinario.nao_encontrado": "Veterinario não encontrado!",
            "veterinario.erro_exclusao": "Erro ao excluir o Veterinário",

            #Tela de agenda do dia 
            "agenda.agenda_dia": "Agenda do dia",
            "agenda.agenda_data": "Agenda por data",
            "agenda.data_dia": "Data (AAAA-MM-DD):",
            "agenda.busca": "Buscar",
            "agenda.marcar_concluido": "Marcar concluído",
            "agenda.selecionar_agendamento": "Selecione um agendamento na lista",
            "agenda.nao_encontrado": "Agendamento não encontrado",
            "agenda.concluido": "Concluido",
            "agenda.marcado_concluido": "Agendamento marcado como concluído!",
            "agenda.servico": "Serviço",
            "agenda.horario": "Horário",
            "agenda.status": "Status",
            "agenda.digite_data": "Digite uma data",

            # Menu principal
            "menu.animal": "Animal",
            "menu.vacina": "Vacina",
            "menu.aplicacao_vacina": "Aplicação de Vacinas",
            "menu.agendamento": "Agendamento",
            "menu.cliente": "Cliente",
            "menu.raca": "Raça",
            "menu.veterinario": "Veterinário",
            "menu.especie": "Espécie",
            "menu.consulta": "Consulta",
            "menu.idioma": "Idioma",
            "menu.sair": "Sair",
            "menu.data_nascimento": "Data de Nascimento:",

        },
        "en": { #ingles
            # Comuns a várias telas

            #Tela de Animal
            "animal.janela_titulo": "Animal CRUD",
            "animal.titulo" : "Animal Registration",
            "animal.dados_frame": "Animal Details",
            "animal.sexo": "Sex:",
            "animal.peso": "Weight:",
            "animal.cliente_id": "Client ID:",
            "animal.especie_id": "Species ID:",
            "animal.raca_id": "Breed ID:",
            "animal.confirmacao_exclusao": "Are you sure you want to delete this animal?",
            "animal.selecionar_animal": "Select an animal from the list.",
            "animal.atualizacao": "Animal updated successfully!",
            "animal.exclusao": "Animal deleted successfully!",
            "animal.nao_encontrado": "Animal not found.",
            "animal.problema_exclusao": "Error deleting animal",

            #Tela de Aplicacao_vacina
            "aplicacao_vacina.janela_titulo": "Vaccine Administration CRUD",
            "aplicacao_vacina.titulo": "Create Vaccine Administration",
            "aplicacao_vacina.dadso_frame": "Vaccine Administration Data",
            "aplicacao_vacina.tipo_servico": "Service Type:",
            "aplicacao_vacina.data_vacina": "Vaccination Date:",
            "aplicacao_vacina.horario_vacina": "Vaccination Time:",
            "aplicacao_vacina.status_vacina": "Vaccination Status:",
            "aplicacao_vacina.animal_id": "Animal ID:",
            "aplicacao_vacina.vacina_id": "Vaccine ID:",
            "aplicacao_vacina.confirmacao_exclusao": "Are you sure you want to delete this vaccine administration record?",
            "aplicacao_vacina.cadastro_sucesso": "Vaccine administration successfully registered!",
            "aplicacao_vacina.selecionar_aplicacao": "Select a vaccine administration record from the list.",
            "aplicacao_vacina.atualizacao": "Vaccine administration successfully updated!",
            "aplicacao_vacina.exclusao": "Vaccine administration successfully deleted!",
            "aplicacao_vacina.nao_encontrado": "Vaccine administration record not found",
            "aplicacao_vacina.problema_exclusao": "Error deleting vaccine administration record.",

            #Tela de Vacina
            "vacina.cadastro_sucesso": "Vaccine registered successfully!",
            "vacina.selecionar_vacina": "Select a vaccine from the list.",
            "vacina.atualizacao": "Vaccine updated successfully!",
            "vacina.exclusao": "Vaccine deleted successfully!",
            "vacina.nao_encontrada": "Vaccine not found.",
            "vacina.problema_exclusao": "Error deleting vaccine",
            "vacina.janela_titulo": "Vaccine CRUD",
            "vacina.dados_frame": "Vaccine Data",
            "vacina.descricao": "Description",
            "vacina.confirmacao_exclusao": "Are you sure you want to delete this vaccine?",
            "vacina.titulo": "Vaccine Creation",

            #Tela de Cliente 
            "cliente.janela_titulo" : "Client Management",
            "cliente.titulo" : "Client Registration",
            "cliente.dados_frame" : "Client Details",
            "cliente.telefone" : "Phone number:",
            "cliente.cpf" : "CPF number:",
            "cliente.confirmacao_exclusao" : "Are you sure you want to delete this client?",
            "cliente.selecionar_animal" : "Select an animal",
            "cliente.cadastro_sucesso" : "Client registered successfully!",
            "cliente.problema_exclusao" : "Error deleting client!!",
            "cliente.atualizacao" : "Client updated!",
            "cliente.selecionar" : "Select a client",
            "cliente.exclusao" : "Client deleted successfully!",
            "cliente.nao_encontrado" : "No client found!",

            #Tela de Raça 
            "raca.janela_titulo": "Breed CRUD",
            "raca.titulo": "Breed Registration",
            "raca.dados_frame": "breed data",
            "raca.confirmacao_exclusao": "Do you really want to delete this breed?",
            "raca.cadastro_sucesso": "Breed registered successfully!",
            "raca.selecione_raca": "Select a breed from the list",
            "raca.raca_atualizada": "Breed updated",
            "raca.exclusao": "Breed successfully deleted",
            "raca.nao_encontrada": "Breed not found",
            "raca.problema_exclusao": "Problems deleting breed",

            #Tela de Agendamento
            "agendamento.janela_titulo":"Appointment CRUD",
            "agendamento.titulo": "Appointment Registration",
            "agendamento.dados": "Appointment Data",
            "agendamento.servico": "Services",
            "agendamento.horario": "Schedules",
            "agendamento.data_agendamento": "Appointment Date",
            "agendamento.status": "Status:",
            "agendamento.confirmacao_exclusao": "Do you really want to delete this appointment?",
            "agendamento.cadastro_sucesso": "Appointment registered",
            "agendamento.selecione_agendamento": "Select an appointment from the list",
            "agendamento.atualizado": "Appointment updated",
            "agendamento.exclusao": "Appointment deleted",
            "agendamento.nao_encontrado": "Appointment not found",
            "agendamento.problema_exclusao": "Problems deleting appointment",
                    
            #Tela de Especie
            "especie.janela_titulo": "Species Registration",
            "especie.dados": "Species Data",
            "especie.adicionar_raca": "Add Breed",
            "especie.confirmacao_exclusao": "Do you really want to delete this species?",
            "especie.selecionar_raca": "Select a breed!",
            "especie.cadastro": "Species successfully registered!",
            "especie.selecione_especie": "Select a species!",
            "especie.raca_a_especie": "Breed successfully added to species!",
            "especie.atualizada": "Species successfully updated!",
            "especie.exclusao": "Species successfully deleted!",
            "especie.nao_encontrada": "Species not found!",
            "especie.problema_exclusao": "Problems deleting species.",

            #Tela de Consulta
            "consulta.janela_titulo": "Consultation CRUD",
            "consulta.titulo": "Consultation Registration",
            "consulta.dados": "Consultation Data",
            "consulta.horario": "Consultation Time",
            "consulta.data": "Consultation Date",
            "consulta.observacao": "Notes",
            "consulta.confirmacao_exclusao": "Do you really want to delete this consultation?",
            "consulta.selecione_veterionario": "Select a veterinarian!",
            "consulta.agendamento": "Consultation successfully scheduled!",
            "consulta.erro_cadastro": "Error registering consultation!",
            "consulta.atualizacao": "Consultation successfully updated!",
            "consulta.selecione_consulta": "Select a consultation from the list:",
            "consulta.nao_encontrada": "Consultation not found!",
            "consulta.erro_exclusao": "Error deleting consultation",

            #Tela de Veterinario
            "veterinario.janela_titulo": "Veterinarians CRUD",
            "veterinario.titulo": "Veterinarian Registration",
            "veterinario.dados": "Veterinarian Data",
            "veterinario.telefone": "Phone: ",
            "veterinario.cpf": "Veterinarian CPF:",
            "veterinario.rg": "RG",
            "veterinario.especialidade": "Specialty:",
            "veterinario.confirmacao_exclusao": "Do you really want to delete this veterinarian?",
            "veterinario.cadastro": "Veterinarian successfully registered!",
            "veterinario.selecione_veterinario": "Select a veterinarian from the list:",
            "veterinario.atualizacao": "Veterinarian successfully updated!",
            "veterinario.exclusao": "Veterinarian successfully deleted!",
            "veterinario.nao_encontrado": "Veterinarian not found!",
            "veterinario.erro_exclusao": "Error deleting the veterinarian",

            # Tela de agenda 
            "agenda.agenda_dia": "Daily schedule",
            "agenda.agenda_data": "Schedule by date",
            "agenda.data_dia": "Date (YYYY-MM-DD):",
            "agenda.busca": "Search",
            "agenda.marcar_concluido": "Mark as completed",
            "agenda.selecionar_agendamento": "Select an appointment from the list",
            "agenda.nao_encontrado": "Schedule not found",
            "agenda.concluido": "Completed",
            "agenda.marcado_concluido": "Appointment marked as completed!",

            # Menu principal
            "menu.animal": "Animal",
            "menu.vacina": "Vaccine",
            "menu.aplicacao_vacina": "Vaccine Administration",
            "menu.agendamento": "Appointment",
            "menu.cliente": "Client",
            "menu.raca": "Breed",
            "menu.veterinario": "Veterinarian",
            "menu.especie": "Species",
            "menu.consulta": "Consultation",
            "menu.idioma": "Language",
            "menu.sair": "Exit",
            "menu.data_nascimento": "Date of Birth:",
            }
    }

    @classmethod # é usado quando tem algum atributo que eu quero que os metodos acessem e modifiquem eles
    def definir(cls, codigo): #cls = um self, que eu passo a propria classe como referencia
        cls.ATUAL = codigo # no codigo eu determino o idioma 

    @classmethod
    def t(cls, chave): # t = é um metodo normalmente de tradução 
        return cls.TEXTOS[cls.ATUAL].get(chave, chave)